
service: poryectofinalaws-danielsalazar

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  apiGateway: 
    shouldStartNameWithService: true

#-----------------FUNCIONES--------------------

functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:  
       - http:
            method: POST
            path: /hacerPedido

            iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: 
          -arn:aws:s3:::poryectofinalaws-daniels-serverlessdeploymentbuck-yc897i4bbzpf
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: 
          - arn cola
      - Effect: Allow
        Action:
          - ses:SendEmail
          - ses:SendRawEmail
        Resource: "*"
            
  obtenerPedido:  
    handler: handler.obtenerPedido
    events:  
       - http:
            method: GET
            path: /obtenerPedido


#--------------RECURSOS---------------


/ bucket para eleiminar un pedido depues de dos dias
resources:
  Resources:
   Bucket-jd:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: poryectofinalaws-daniels-serverlessdeploymentbuck-yc897i4bbzpf
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfterTwoDays
            Status: Enabled
            ExpirationInDays: 2

// bases de datos mysql
  Database-Restaurante:
      Type: AWS::RDS::DBInstance
      Properties:
        DBname: RestauranteDanielSalazar
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        engine: MySQL
        EngineVersion:  5.7
        MasterUsername: admin
        MasterUserPassword: 12345678
        MultiAZ: false
        StorageType: gp2
        PubliclyAccessible: true
        VPCSecurityGroups:
          -  sg-02b764b4eced3a377

    #  grupo de seguridad 
    RDSSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId: sg-02b764b4eced3a377
        IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0

//cola con delay de 15s
Queue-DanielSalazar:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: order-queue
        DelaySeconds: 15
        MessageRetentionPeriod: 1036800